/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.mercell.kafka.connect.postgres

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
